import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css']
})
export class AutoGeneratedComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit() {

  }

  handleCricketLink(): void {
    console.log('ROHIT:::navigating to cricket....');
    this.router.navigate(['/cricket']);
  }

}
